# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["barter", "client"]

[patch.crates-io]

# Ensure any transitive dependencies also use the local geo/geo-types
barter = { path = "barter" }
# geo-types = { path = "geo-types" }
